In [10]:
import pandas as pd
import re

In [11]:
true_value_df = pd.read_csv('../robot_true_captions.csv')
evaluation_df = pd.read_csv('../robot_evaluation_captions_22.csv')

evaluation_df.head()

  object_id camera_id                                 evaluation_caption
0    BigJar       PC1  one full transparent closed cylindrical plasti...
1    BigJar       PC2  one full opaque closed cylindrical plastic jar...
2    BigJar       PC3  one full opaque closed cylindrical plastic jar...
3    BigJar       PC4  one empty transparent closed cylindrical plast...
4    BigJar       PC5  one empty transparent closed cylindrical plast...

In [12]:
true_value_captions = true_value_df['true_caption'].values
evaluation_captions = evaluation_df['evaluation_caption'].values

In [13]:
chunk_size = 9
init_value = 0

true_finishes = []
caption_vote_finishes = []

# i -> 0 - 49
for i in range(init_value, int(len(evaluation_captions) / chunk_size)):
    current_range = int(i * chunk_size)
    true_caption = true_value_captions[i]
    evaluation_caption = evaluation_captions[current_range:current_range + chunk_size]

    true_finishes.append(re.search("\w+(?=\s*finish[^/])", true_caption).group())
    current_caption_finishes = []
    for caption in evaluation_caption:
        current_caption_finishes.append(re.search("\w+(?=\s*finish[^/])", caption).group())
        
    caption_vote_finishes.append(max(set(current_caption_finishes), key=current_caption_finishes.count))

In [14]:
finish_df = pd.DataFrame()
finish_df['true_value'] = true_finishes
finish_df['evaluation'] = caption_vote_finishes

In [15]:
finish_df

   true_value evaluation
0       twist      twist
1       twist      twist
2       twist      twist
3       twist      twist
4       twist      twist
5       twist      twist
6       twist      twist
7       twist      twist
8       twist      twist
9       twist      twist
10      twist      twist
11      twist      twist
12      twist      twist
13      twist      twist
14      twist      twist
15      twist      twist
16      twist      twist
17      twist      twist
18      twist      twist
19      twist      twist
20      twist      twist
21      twist      twist
22      twist      twist
23      twist      twist
24      twist      twist
25       snap      twist
26       snap      twist
27       snap       snap
28       snap      twist
29       snap       snap
30       snap       snap
31       snap       snap
32       snap       snap
33       snap       snap
34       snap      twist
35       snap       snap
36       snap      twist
37       snap      twist
38       snap      twist
39       snap      twist
40       snap      twist
41       snap       snap
42       snap      twist
43       snap       snap
44       snap       snap
45       snap       snap
46       snap      twist
47       snap       snap
48       snap       snap
49       snap      twist

In [16]:
print(pd.crosstab(finish_df.true_value, finish_df.evaluation))

evaluation  snap  twist
true_value
snap          13     12
twist          0     25